# Site settings
title: "Eugene Y. Q. Shen"
email: "eugene@eyqs.ca"
url:   "https://eyqs.ca"
baseurl: ""
description: "The home page of Eugene Y. Q. Shen, a wannabe programmer, awful pianist, and first-year Engineering student. Welcome to my site on the web!"
github_username: eyqs

# Build settings
safe:        true
show_drafts: false
timezone:    America/Vancouver
permalink:   /blogs/:short_year:month-:title/

# Default settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Eugene Y. Q. Shen"
  -
    scope:
      path: "blogs"
    values:
      layout: "post"
      excerpt_separator: <!--more-->
